### ISSUE TITLE
TypeError: this.viewSelector.addSearchProvider is not a function

### ISSUE THREAD

**Issue by franziskuskiefer** [bmh1980/gnome-shell-extension-searchrecentlyused#4]
I get the following error when installing/enabling the extension

`Extension "searchrecentlyused@bmh1980de.gmail.com" had error: TypeError: this.viewSelector.addSearchProvider is not a function`

I'm on Arch with 3.12

**Comment by bmh1980** [comment]
What extension version do you use?

**Comment by franziskuskiefer** [comment]
I tried the version from https://extensions.gnome.org/. But also just installed manually from git and got the same error.

**Comment by bmh1980** [comment]
After reading the 3.12 scripts I have found the problem, but no solution. It’s a GS bug. https://bugzilla.gnome.org/show_bug.cgi?id=727461

**Comment by bmh1980** [comment]
I will leave this issue open till the GS bug is fixed.

**Comment by franziskuskiefer** [comment]
I'm not entirely sure if it's a GS bug. The linked bug report seems related, but other search providers work (e.g., https://github.com/hamiller/tracker-search-provider).

**Comment by bmh1980** [comment]
Are you sure? tracker-search-provider supports only GS 3.10, it calls the same function like my search providers (Main.overview.addSearchProvider) and your error message comes from a GS internal JS.

**Comment by franziskuskiefer** [comment]
Check the 3.12 branch :wink: I think there's also the solution to the problem.

```
Main.overview.viewSelector._searchResults._searchSystem.addProvider(trackerSearchProviderFiles);
```

**Comment by bmh1980** [comment]
I will commit a fix for this problem. Can you please check if it works? Thanks.

**Comment by franziskuskiefer** [comment]
This fixes the described error, but not the extension. Now the entire search in GS overview breaks with the extension enabled. That's because you set `this.searchSystem = null` and then use it, which results in an error while searching.

**Comment by bmh1980** [comment]
That isn’t the problem. The GS developers has switched in the past from an async/sync system, to an sync system. Now they have switched to an async search system. It’s really annoying that the GS developers are breaking with every new minor release the API and doesn’t provide any documentation.

**Comment by bmh1980** [comment]
The new fix I will push should solve it. I’ve tried it with Arch. But only with VBox and in it I haven’t really documents to test in a real world.

**Comment by franziskuskiefer** [comment]
yes the API changes are annoying.. the new version seems to work. thanks for the fix :+1:
