### ISSUE TITLE
missing search results

### ISSUE THREAD

**Issue by franziskuskiefer** [bmh1980/gnome-shell-extension-searchrecentlyused#5]
After getting the extension to work now there seems to be a problem within the search function. It does not return everything that is in the recently used files in nautilus. In particular, it shows different results depending on how fast I type. The only way to get the expected result is to paste a considerable part of the search term into the search field. It seems the search only uses the first x typed letters and does not update.

It also shows only _one_ search result. Not sure if that is intentionally.

**Comment by bmh1980** [comment]
See http://bmh1980.github.io/gnome-shell-extension-searchrecentlyused/ why
